<?php

//PARA EXECUTAR UM SERVIDOR WEB PARA TESTE BASTA UTILIZAR O COMANDO 

//A PRIMEIRA COISA QUE O SERVIDOR BUSCA PARA EXECUTAR NA PAGINA É UM INDEX

//UMA FORMA DE EXECUTAR O ARQUIVO SEM O INDEX :: http://localhost:8080/depositando_valor.php

//php -S localhost:8080